"""
OfflineScribe — Meeting Notes Export API route.

Endpoint:
    POST /api/export

Per API_CONTRACT.md section 7:
    Request:  {"format": "markdown", "transcript": "...", "summary": "...", "decisions": [...], "action_items": [...]}
    Response: Downloadable .md file containing transcript + summary + action items.
"""

import logging
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Response
from pydantic import BaseModel

logger = logging.getLogger("offlinescribe.export")

router = APIRouter()


class ActionItemModel(BaseModel):
    task: str
    owner: str | None = None


class ExportRequest(BaseModel):
    format: str = "markdown"
    transcript: str | None = ""
    summary: str | None = ""
    decisions: list[str] | None = None
    action_items: list[ActionItemModel] | None = None


@router.post("/api/export")
async def export_notes(request: ExportRequest) -> Response:
    """
    Generate and return a downloadable Markdown report of the meeting.
    """
    logger.info("Generating export report (format=%s)", request.format)

    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")

    md_lines = [
        "# 📝 OfflineScribe — Meeting Notes & Summary",
        f"**Date:** {date_str}  ",
        "**Generated by:** OfflineScribe (On-Device Snapdragon AI Assistant)  ",
        "",
        "---",
        "",
        "## 📌 Executive Summary",
        request.summary or "No summary generated for this session.",
        "",
        "## 🎯 Key Decisions",
    ]

    if request.decisions and len(request.decisions) > 0:
        for dec in request.decisions:
            md_lines.append(f"- ✅ {dec}")
    else:
        md_lines.append("_No explicit decisions recorded._")

    md_lines.extend([
        "",
        "## 📋 Action Items",
    ])

    if request.action_items and len(request.action_items) > 0:
        md_lines.append("| Task | Assignee |")
        md_lines.append("| :--- | :--- |")
        for item in request.action_items:
            owner = f"**{item.owner}**" if item.owner else "_Unassigned_"
            md_lines.append(f"| {item.task} | {owner} |")
    else:
        md_lines.append("_No action items recorded._")

    md_lines.extend([
        "",
        "---",
        "",
        "## 🎙 Full Transcript",
        "",
        request.transcript or "_No transcript text recorded._",
        "",
        "---",
        "_Exported securely on-device with zero internet connection requirement._",
    ])

    markdown_content = "\n".join(md_lines)
    filename = f"OfflineScribe_Meeting_Notes_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"

    return Response(
        content=markdown_content,
        media_type="text/markdown",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "Access-Control-Expose-Headers": "Content-Disposition",
        },
    )
